-- DROP SCHEMA public;

CREATE SCHEMA public AUTHORIZATION pg_database_owner;

COMMENT ON SCHEMA public IS 'standard public schema';

-- DROP TYPE public."e_gender";

CREATE TYPE public."e_gender" AS ENUM (
	'MALE',
	'FEMALE',
	'OTHER');

-- DROP TYPE public."e_user_status";

CREATE TYPE public."e_user_status" AS ENUM (
	'ACTIVE',
	'INACTIVE',
	'NONE');

-- DROP TYPE public."e_user_type";

CREATE TYPE public."e_user_type" AS ENUM (
	'OWNER',
	'ADMIN',
	'USER');

-- DROP TYPE public."gender";

CREATE TYPE public."gender" AS ENUM (
	'FEMALE',
	'MALE',
	'OTHER');

-- DROP TYPE public."userstatus";

CREATE TYPE public."userstatus" AS ENUM (
	'ACTIVE',
	'INACTIVE',
	'NONE');

-- DROP TYPE public."usertype";

CREATE TYPE public."usertype" AS ENUM (
	'ADMIN',
	'OWNER',
	'USER');

-- DROP SEQUENCE tbl_address_id_seq;

CREATE SEQUENCE tbl_address_id_seq
    INCREMENT BY 1
    MINVALUE 1
    MAXVALUE 9223372036854775807
    START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE tbl_area_id_seq;

CREATE SEQUENCE tbl_area_id_seq
    INCREMENT BY 1
    MINVALUE 1
    MAXVALUE 2147483647
    START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE tbl_garden_id_seq;

CREATE SEQUENCE tbl_garden_id_seq
    INCREMENT BY 1
    MINVALUE 1
    MAXVALUE 2147483647
    START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE tbl_group_has_user_id_seq;

CREATE SEQUENCE tbl_group_has_user_id_seq
    INCREMENT BY 1
    MINVALUE 1
    MAXVALUE 2147483647
    START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE tbl_group_id_seq;

CREATE SEQUENCE tbl_group_id_seq
    INCREMENT BY 1
    MINVALUE 1
    MAXVALUE 2147483647
    START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE tbl_group_role_id_seq;

CREATE SEQUENCE tbl_group_role_id_seq
    INCREMENT BY 1
    MINVALUE 1
    MAXVALUE 2147483647
    START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE tbl_permission_id_seq;

CREATE SEQUENCE tbl_permission_id_seq
    INCREMENT BY 1
    MINVALUE 1
    MAXVALUE 2147483647
    START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE tbl_plant_id_seq;

CREATE SEQUENCE tbl_plant_id_seq
    INCREMENT BY 1
    MINVALUE 1
    MAXVALUE 9223372036854775807
    START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE tbl_role_has_permission_id_seq;

CREATE SEQUENCE tbl_role_has_permission_id_seq
    INCREMENT BY 1
    MINVALUE 1
    MAXVALUE 2147483647
    START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE tbl_role_has_permission_permission_id_seq;

CREATE SEQUENCE tbl_role_has_permission_permission_id_seq
    INCREMENT BY 1
    MINVALUE 1
    MAXVALUE 2147483647
    START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE tbl_role_has_permission_role_id_seq;

CREATE SEQUENCE tbl_role_has_permission_role_id_seq
    INCREMENT BY 1
    MINVALUE 1
    MAXVALUE 2147483647
    START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE tbl_role_id_seq;

CREATE SEQUENCE tbl_role_id_seq
    INCREMENT BY 1
    MINVALUE 1
    MAXVALUE 2147483647
    START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE tbl_user_has_role_id_seq;

CREATE SEQUENCE tbl_user_has_role_id_seq
    INCREMENT BY 1
    MINVALUE 1
    MAXVALUE 2147483647
    START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE tbl_user_has_role_role_id_seq;

CREATE SEQUENCE tbl_user_has_role_role_id_seq
    INCREMENT BY 1
    MINVALUE 1
    MAXVALUE 2147483647
    START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE tbl_user_has_role_user_id_seq;

CREATE SEQUENCE tbl_user_has_role_user_id_seq
    INCREMENT BY 1
    MINVALUE 1
    MAXVALUE 9223372036854775807
    START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE tbl_user_id_seq;

CREATE SEQUENCE tbl_user_id_seq
    INCREMENT BY 1
    MINVALUE 1
    MAXVALUE 9223372036854775807
    START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE tbl_vase_id_seq;

CREATE SEQUENCE tbl_vase_id_seq
    INCREMENT BY 1
    MINVALUE 1
    MAXVALUE 2147483647
    START 1
	CACHE 1
	NO CYCLE;-- public.tbl_permission definition

-- Drop table

-- DROP TABLE tbl_permission;

CREATE TABLE tbl_permission (
                                id serial4 NOT NULL,
                                "name" varchar(255) NOT NULL,
                                created_at timestamp(6) NULL,
                                updated_at timestamp(6) NULL,
                                description varchar(255) NULL,
                                CONSTRAINT tbl_permission_pkey PRIMARY KEY (id)
);


-- public.tbl_plant definition

-- Drop table

-- DROP TABLE tbl_plant;

CREATE TABLE tbl_plant (
                           id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                           created_at timestamp(6) NULL,
                           updated_at timestamp(6) NULL,
                           description text NULL,
                           image varchar(255) NULL,
                           plant_name varchar(255) NULL,
                           introduction text NULL,
                           image_source varchar(255) NULL,
                           title varchar(255) NULL,
                           url varchar(255) NULL,
                           table_data jsonb NULL,
                           care_data jsonb NULL,
                           CONSTRAINT tbl_plant_pkey PRIMARY KEY (id)
);


-- public.tbl_role definition

-- Drop table

-- DROP TABLE tbl_role;

CREATE TABLE tbl_role (
                          id serial4 NOT NULL,
                          "name" varchar(255) NOT NULL,
                          created_at timestamp(6) NULL,
                          updated_at timestamp(6) NULL,
                          description varchar(255) NULL,
                          CONSTRAINT tbl_role_pkey PRIMARY KEY (id)
);


-- public.tbl_user definition

-- Drop table

-- DROP TABLE tbl_user;

CREATE TABLE tbl_user (
                          id bigserial NOT NULL,
                          first_name varchar(255) NOT NULL,
                          last_name varchar(255) NOT NULL,
                          date_of_birth date NOT NULL,
                          "gender" public."e_gender" NOT NULL,
                          phone varchar(15) NULL,
                          email varchar(255) NULL,
                          username varchar(255) NOT NULL,
                          "password" varchar(255) NULL,
                          status public."e_user_status" NOT NULL,
                          "type" public."e_user_type" NOT NULL,
                          created_at timestamp(6) DEFAULT now() NULL,
                          updated_at timestamp(6) DEFAULT now() NULL,
                          CONSTRAINT tbl_user_pkey PRIMARY KEY (id)
);


-- public.tbl_address definition

-- Drop table

-- DROP TABLE tbl_address;

CREATE TABLE tbl_address (
                             id bigserial NOT NULL,
                             apartment_number varchar(255) NULL,
                             floor varchar(255) NULL,
                             building varchar(255) NULL,
                             street_number varchar(255) NULL,
                             street varchar(255) NULL,
                             city varchar(255) NULL,
                             country varchar(255) NULL,
                             address_type int4 NULL,
                             user_id int8 NULL,
                             created_at timestamp(6) DEFAULT now() NULL,
                             updated_at timestamp(6) DEFAULT now() NULL,
                             CONSTRAINT tbl_address_pkey PRIMARY KEY (id),
                             CONSTRAINT fk_address_to_user FOREIGN KEY (user_id) REFERENCES tbl_user(id)
);


-- public.tbl_garden definition

-- Drop table

-- DROP TABLE tbl_garden;

CREATE TABLE tbl_garden (
                            id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
                            created_at timestamp(6) NULL,
                            updated_at timestamp(6) NULL,
                            garden_name varchar(255) NULL,
                            user_id int8 NULL,
                            CONSTRAINT tbl_garden_pkey PRIMARY KEY (id),
                            CONSTRAINT fk1esqa9ibbnbvo27rkdyyph6go FOREIGN KEY (user_id) REFERENCES tbl_user(id)
);


-- public.tbl_group definition

-- Drop table

-- DROP TABLE tbl_group;

CREATE TABLE tbl_group (
                           id serial4 NOT NULL,
                           "name" varchar(255) NOT NULL,
                           role_id serial4 NOT NULL,
                           created_at timestamp(6) NULL,
                           updated_at timestamp(6) NULL,
                           description varchar(255) NULL,
                           CONSTRAINT tbl_group_pkey PRIMARY KEY (id),
                           CONSTRAINT fk_group_to_role FOREIGN KEY (role_id) REFERENCES tbl_role(id)
);


-- public.tbl_group_has_user definition

-- Drop table

-- DROP TABLE tbl_group_has_user;

CREATE TABLE tbl_group_has_user (
                                    id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
                                    created_at timestamp(6) NULL,
                                    updated_at timestamp(6) NULL,
                                    group_id int4 NULL,
                                    user_id int8 NULL,
                                    CONSTRAINT tbl_group_has_user_pkey PRIMARY KEY (id),
                                    CONSTRAINT fkk23xt6t0rhoc1s185sekeayf9 FOREIGN KEY (group_id) REFERENCES tbl_group(id),
                                    CONSTRAINT fkqpbvdln7wyp9dnjvrx0mrrnk1 FOREIGN KEY (user_id) REFERENCES tbl_user(id)
);


-- public.tbl_role_has_permission definition

-- Drop table

-- DROP TABLE tbl_role_has_permission;

CREATE TABLE tbl_role_has_permission (
                                         id serial4 NOT NULL,
                                         role_id serial4 NOT NULL,
                                         permission_id serial4 NOT NULL,
                                         created_at timestamp(6) NULL,
                                         updated_at timestamp(6) NULL,
                                         CONSTRAINT tbl_role_has_permission_pkey PRIMARY KEY (id),
                                         CONSTRAINT fk_role_has_permission_to_permission FOREIGN KEY (permission_id) REFERENCES tbl_permission(id),
                                         CONSTRAINT fk_role_has_permission_to_role FOREIGN KEY (role_id) REFERENCES tbl_role(id)
);


-- public.tbl_user_has_role definition

-- Drop table

-- DROP TABLE tbl_user_has_role;

CREATE TABLE tbl_user_has_role (
                                   id serial4 NOT NULL,
                                   user_id bigserial NOT NULL,
                                   role_id serial4 NOT NULL,
                                   created_at timestamp(6) NULL,
                                   updated_at timestamp(6) NULL,
                                   CONSTRAINT tbl_user_has_role_pkey PRIMARY KEY (id),
                                   CONSTRAINT fk_user_has_role_to_role FOREIGN KEY (role_id) REFERENCES tbl_role(id),
                                   CONSTRAINT fk_user_has_role_to_user FOREIGN KEY (user_id) REFERENCES tbl_user(id)
);


-- public.tbl_area definition

-- Drop table

-- DROP TABLE tbl_area;

CREATE TABLE tbl_area (
                          id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
                          created_at timestamp(6) NULL,
                          updated_at timestamp(6) NULL,
                          area_name varchar(255) NULL,
                          image varchar(255) NULL,
                          garden_id int4 NULL,
                          CONSTRAINT tbl_area_pkey PRIMARY KEY (id),
                          CONSTRAINT fk7l5lcxqm5y6ellfdf2jfr4mk5 FOREIGN KEY (garden_id) REFERENCES tbl_garden(id)
);


-- public.tbl_vase definition

-- Drop table

-- DROP TABLE tbl_vase;

CREATE TABLE tbl_vase (
                          id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
                          created_at timestamp(6) NULL,
                          updated_at timestamp(6) NULL,
                          vase_name varchar(255) NULL,
                          area_id int4 NULL,
                          plant_id int8 NULL,
                          device_id int8 NULL,
                          CONSTRAINT tbl_vase_pkey PRIMARY KEY (id),
                          CONSTRAINT fk587mdr8wesov38o7o4akglpe4 FOREIGN KEY (area_id) REFERENCES tbl_area(id),
                          CONSTRAINT fkpj3qg8qixg5vkg0ddecow5f8i FOREIGN KEY (plant_id) REFERENCES tbl_plant(id)
);