spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  config:
    activate:
      on-profile: dev
  devtools:
    add-properties: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5432}/postgres
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: none
  sendgrid:
    apiKey: ${SENDGRID_API_KEY}
    from-email: ${SENDGRID_FROM_EMAIL}
    template-id: ${SENDGRID_TEMPLATE_ID}
    verification-link: ${SENDGRID_VERIFICATION_LINK}

# application-dev.yml
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
openapi:
  service:
    api-docs: backend-service
    server: http://localhost:${server.port}
    title: Backend service
    version: 1.0.0

jwt:
  expiryMinutes: 5
  expiryDays: 14
  accessKey: ${JWT_ACCESS_SECRET}
  refreshKey: ${JWT_REFRESH_SECRET}

app:
  file:
    storage-dir: ${STORAGE_DIR}
    download-prefix: ${DOWNLOAD_PREFIX}
