spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  config:
    activate:
      on-profile: dev
  devtools:
    add-properties: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${PGHOST}/${PGDATABASE}
    username: ${PGUSER}
    password: ${PGPASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: none
  sendgrid:
    apiKey: ${SENDGRID_API_KEY}
    from-email: ${SENDGRID_FROM_EMAIL}
    template-id: ${SENDGRID_TEMPLATE_ID}
    verification-link: ${SENDGRID_VERIFICATION_LINK}
  mqtt:
    server: l21da1a1.ala.asia-southeast1.emqxsl.com
    port: 8883
    client-id: client
    username: esp32_device
    password: your_password_123
    topic: smart_garden/data
    auto-reconnect: true
    connection-timeout: 30
    keep-alive-interval: 60
#  data:
#    mongodb:
#      uri: mongodb://${MONGO_USER}:${MONGO_PASSWORD}@${MONGO_HOST}:27017/${MONGO_DB}?authSource=admin
#      auto-index-creation: true

# application-dev.yml
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
openapi:
  service:
    api-docs: backend-service
    server: http://localhost:${server.port}
    title: Backend service
    version: 1.0.0

jwt:
  expiryMinutes: 60
  expiryDays: 14
  accessKey: ${JWT_ACCESS_SECRET}
  refreshKey: ${JWT_REFRESH_SECRET}

cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME}
  api-key: ${CLOUDINARY_API_KEY}
  api-secret: ${CLOUDINARY_API_SECRET}
app:
  file:
    download-prefix: ${DOWNLOAD_PREFIX}
